export const Data = [
  {
    id: 1,
    name: "Name_NFT_1",
    price: "20",
    image: "/img_nft_big.svg",
    description: "Uma coleção incomparável",
  },
  {
    id: 2,
    name: "Name_NFT_2",
    price: "20",
    image: "/img_nft_big2.svg",
    description: "Uma coleção incomparável",
  },
  {
    id: 3,
    name: "Name_NFT_3",
    price: "20",
    image: "/img_nft_big3.svg",
    description: "Uma coleção incomparável",
  },
  {
    id: 4,
    name: "Name_NFT_4",
    price: "20",
    image: "/img_nft_big4.svg",
    description: "Uma coleção incomparável",
  },
  {
    id: 5,
    name: "Name_NFT_5",
    price: "20",
    image: "/img_nft_big5.svg",
    description: "Uma coleção incomparável",
  },
  {
    id: 6,
    name: "Name_NFT_6",
    price: "20",
    image: "/img_nft_big2.svg",
    description: "Uma coleção incomparável",
  },
  {
    id: 7,
    name: "Name_NFT_7",
    price: "20",
    image: "/img_nft_big3.svg",
    description: "Uma coleção incomparável",
  },
  {
    id: 8,
    name: "Name_NFT_8",
    price: "20",
    image: "/img_nft_big4.svg",
    description: "Uma coleção incomparável",
  },
  {
    id: 9,
    name: "Name_NFT_9",
    price: "20",
    image: "/img_nft_big5.svg",
    description: "Uma coleção incomparável",
  },
  {
    id: 10,
    name: "Name_NFT_10",
    price: "20",
    image: "/img_nft_big2.svg",
    description: "Uma coleção incomparável",
  },
];
